name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.11', '3.12']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -U tox
    - name: Add secrets to .env
      run: |
        echo "EXAMPLE_HEBE_USERNAME=${{ secrets.EXAMPLE_HEBE_USERNAME }}" >> .env
        echo "EXAMPLE_HEBE_PASSWORD=${{ secrets.EXAMPLE_HEBE_PASSWORD }}" >> .env
    - name: Test
      env:
        EXAMPLE_HEBE_USERNAME: ${{ env.EXAMPLE_HEBE_USERNAME }}
        EXAMPLE_HEBE_PASSWORD: ${{ env.EXAMPLE_HEBE_PASSWORD }}
      run: python -m tox -e py
